name: My first Workflow 

on: push 

jobs:
   first_job:
     runs-on:ubuntu-latest
     step:
     - name: :Welcome Message
       run: echo "My First GitHub Actions Job"

      - name: List files 
        run: ls 
      
      - name: Read file
        run : cat README.md